apiVersion : apps/v1
kind: Deployment
metadata:
 name: voting-deployment
 labels:
   app : demo-voting-app
spec:
 template:
  metadata:
   name: voting
   labels:
    app: pod-voting
    tier: frontend-voting
  spec:
   containers:
    - name: examplevotingapp-vote
      image: dockersamples/examplevotingapp_vote
      ports:
       - containerPort: 80
 replicas: 3
 selector:
  matchLabels:
   app: pod-voting
   tier: frontend-voting
