apiVersion: v1
kind: Service
metadata:
 name: service-resultados

spec:
 type: NodePort
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30010
 selector:
  app: pod-resultados
  tier: frontend-resultados
