apiVersion : apps/v1
kind: Deployment
metadata:
 name: myapp-rs-frontend
 labels:
   app: myapp
   type: frontend
spec:
 template:
  metadata:
   name: mysql
   labels:
    app: myapp
    type: frontend
  spec:
   containers:
    - name: nginx-container
      image: nginx:1.15
 replicas: 2
 selector:
  matchLabels:
   app: myapp
   type: frontend
