apiVersion : apps/v1
kind: Deployment
metadata:
 name: myapp-redis
 labels:
   app: myapp
   type: frontend
spec:
 template:
  metadata:
   name: mysql
   labels:
    app: myapp
    type: frontend
  spec:
   containers:
    - name: redis
      image: redis:5
 replicas: 2
 selector:
  matchLabels:
   app: myapp
   type: frontend
