apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume2
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/centos/volumenes/mysql-pv-volume2"